// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5djjOw2WivxLdJW4vv-8f7EAn_od3uE0',
    appId: '1:1056545160384:web:3b7d7dd0729a01993d8125',
    messagingSenderId: '1056545160384',
    projectId: 'ore-locks',
    authDomain: 'ore-locks.firebaseapp.com',
    databaseURL: 'https://ore-locks-default-rtdb.firebaseio.com',
    storageBucket: 'ore-locks.appspot.com',
    measurementId: 'G-YLLZJQ8CWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAysaNiFECZdkumTmE57-_ZTg0v3MthKQM',
    appId: '1:1056545160384:android:65780c5b5dd448123d8125',
    messagingSenderId: '1056545160384',
    projectId: 'ore-locks',
    databaseURL: 'https://ore-locks-default-rtdb.firebaseio.com',
    storageBucket: 'ore-locks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB72WeHo11yY8mS3Wu6EVcMxbYVfc6mpw8',
    appId: '1:1056545160384:ios:c3564c53bb47485a3d8125',
    messagingSenderId: '1056545160384',
    projectId: 'ore-locks',
    databaseURL: 'https://ore-locks-default-rtdb.firebaseio.com',
    storageBucket: 'ore-locks.appspot.com',
    iosClientId: '1056545160384-apq8ave5e52se75onak8qsu5ekoc2j4c.apps.googleusercontent.com',
    iosBundleId: 'ore',
  );
}
